if: tag IS present

language: android
android:
  components:
  - build-tools-28.0.2
  - android-28

script: "./build.sh"

deploy:
  provider: releases
  api_key:
    secure: Ka20YuuDqxxzNprL52xBqJS7ZI2q4X1OGw391tDekDwQR89Yxsn+0hARPkK0ua2MpyrAmGCI4wAK83QDpswsqhvopJmDJ72vSHvaAUXCrnXnLmzm6vyP5UYl/Q57NdIdBUEPF73bXtW0Ofwzogy7WzaEjj6DuLP/88SY+IixaCAzNl512uqs6TyYiKhH9Yp3NzYmya/xPctUBWRSTnTyJ0682g6rka9qh//1AsqZeC0Wm6CtwrWBsogzcBqAFvso+e6ZxZ4NHsXf8CroIVAB3oho6veAJLf5o6Vw3x44smjgdEWwBHO9xXqaFaD70bKBtdfTSeAA5o4z05669U5bLBnKy7uJHrWuJI2arrNIcMsZoie8Faloon/L9TsK4UOV4gCWIJcm0qLd42tLbWewQQobgv417YyxhTibltpka4V0U6r9pzv0gFDBQyQm6G1ouBnB+8wKHAU5fjufOPt0MlDZYKr2HzyEAFikOkRxeDxwLuNSJ2HqXE0LB6dHfoMjK4r67g6l1iHjQ92KDr2Wf+QxthmKsoPuWNoa2P92aBlxJKcNWDhhUFqwno4i5lKqZ1JfJ/VFFdsiP3Zgoh7TtxJEgdnp0hUPRqtZkflSay4qN7d4H1eAwY/q4NCejp/Uh3A8ygI1bJOwdZWnMhw9moXsFZkUYOY9K1FvEblqDn8=
  file_glob: true
  file: "*.zip"
  skip_cleanup: true
  on:
    tags: true
